name: Control Railway Deployment

on:
  schedule:
    - cron: "30 6 * * *"  # Start bot every day at 6:30 AM UTC (10:00 AM IRST)
    - cron: "30 0 * * *"  # Stop bot every day at 12:30 AM UTC (4:00 AM IRST)
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  control-railway:
    runs-on: ubuntu-latest
    steps:
      - name: Start Railway Deployment
        if: ${{ github.event_name == 'schedule' && startsWith(github.event.schedule, '30 6') }}
        run: |
          curl -X POST "https://backboard.railway.app/graphql/v2" \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"query":"mutation { deploymentCreate(input: {projectId: \"${{ secrets.RAILWAY_PROJECT_ID }}\"}) { id } }"}'

      - name: Stop Railway Deployment
        if: ${{ github.event_name == 'schedule' && startsWith(github.event.schedule, '30 0') }}
        run: |
          curl -X POST "https://backboard.railway.app/graphql/v2" \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"query":"mutation { deploymentDelete(input: {id: \"${{ secrets.RAILWAY_PROJECT_ID }}\"}) { id } }"}'
